[package]
name = "vacationers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
chrono = "0.4.26"
termion = "2.0.1"
